pub mod ai;
pub mod scanner;

use anyhow::Result;
use std::path::Path;

use crate::engine::config::Config;
use crate::engine::doctor::find_available_agent;

pub fn generate_initial_config(
    root_dir: &Path,
    force_ai: bool,
    agent_override: Option<&str>,
) -> Result<(String, String)> {
    // 1. If AI is explicitly forced
    if force_ai {
        let (yaml, agent_name) = ai::generate_config_via_ai(root_dir, agent_override)?;
        return Ok((yaml, format!("AI Agent CLI [{}]", agent_name)));
    }

    // 2. If AI agent is available on system, try AI generation with fallback
    if let Some(agent_desc) = find_available_agent(agent_override) {
        if let Ok((yaml, agent_name)) = ai::generate_config_via_ai(root_dir, Some(&agent_desc.name)) {
            return Ok((yaml, format!("AI Agent CLI [{}]", agent_name)));
        }
    }

    // 3. Fallback: Fast Heuristic Rule Scanner
    let scanned = scanner::scan_directory(root_dir);
    let cfg = Config {
        processes: scanned.processes,
    };

    let yaml_raw = serde_yaml::to_string(&cfg)?;
    let mut header = String::from("# Generated by procman init (Heuristic Scanner)\n");
    if !scanned.detected_frameworks.is_empty() {
        header.push_str(&format!(
            "# Detected frameworks: {}\n",
            scanned.detected_frameworks.join(", ")
        ));
    }
    header.push('\n');
    header.push_str(&yaml_raw);

    let engine_label = if scanned.detected_frameworks.is_empty() {
        "Heuristic Scanner".to_string()
    } else {
        format!("Heuristic Scanner [{}]", scanned.detected_frameworks.join(", "))
    };

    Ok((header, engine_label))
}
